---
name: Update Sogou Input

on:
  schedule:
    - cron: "0 16 * * *" # Run every day at 16:00 UTC (00:00 Beijing Time)
  workflow_dispatch: {} # Allow manual triggering

# Add permissions configuration
permissions:
  contents: write
  packages: read

jobs:
  update-sogou-input:
    runs-on: macos-latest
    env:
      SKIP_RELEASE: false
      VERSION: "0.0.0"
      SHA256: "placeholder"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download latest Sogou Input
        run: |
          curl -L "https://pinyin.sogou.com/mac/softdown.php" -o sogou_input_temp.zip
          unzip -q sogou_input_temp.zip -d extracted
          APP_PATH=$(find extracted -name "*.app" -type d | head -n 1)

          if [ -z "$APP_PATH" ]; then
            echo "No Sogou app found in extracted directory"
            exit 1
          fi

          # Extract version using plist instead of defaults command
          VERSION=$(plutil -p "$APP_PATH/Contents/Info.plist" | \
            grep CFBundleShortVersionString | awk -F'"' '{print $4}')
          SHA256=$(shasum -a 256 sogou_input_temp.zip | awk '{print $1}')

          # Rename the downloaded file to include version number
          mv sogou_input_temp.zip "sogou_input_v${VERSION}.zip"

          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
          echo "SHA256=$SHA256" >> "$GITHUB_ENV"

          # Check if this version already exists
          if git ls-remote --tags origin | grep -q "refs/tags/v$VERSION"; then
            echo "Version $VERSION already exists, skipping release"
            echo "SKIP_RELEASE=true" >> "$GITHUB_ENV"
          else
            echo "SKIP_RELEASE=false" >> "$GITHUB_ENV"
          fi

          # Verify env var is set
          echo "SKIP_RELEASE value: $SKIP_RELEASE"

      - name: Create release
        if: ${{ env.SKIP_RELEASE != 'true' }}
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: Sogou Input v${{ env.VERSION }}
          body: |
            # Sogou Input Method v${{ env.VERSION }}

            Official website: https://pinyin.sogou.com/mac/
            Download link: https://pinyin.sogou.com/mac/softdown.php

            SHA256: ${{ env.SHA256 }}

            ## System Requirements
            - macOS 10.14 (Mojave) or later
            - Intel and Apple Silicon (M1/M2/M3) Mac supported

            This is an automated release of the Sogou Input Method for macOS.

            ## Installation
            ```
            brew install --cask recronin/sogou-input/sogou-input
            ```

            > **Note:** Please download the `sogou_input_v${{ env.VERSION }}.zip`
            > file above. Please DO NOT use the auto-generated "Source code" files
            > at the bottom.
          files: sogou_input_v${{ env.VERSION }}.zip
          generate_release_notes: false
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Cask file
        if: ${{ env.SKIP_RELEASE != 'true' }}
        run: |
          # Get repository info
          REPO_OWNER=$(echo "$GITHUB_REPOSITORY" | cut -d '/' -f 1)
          REPO_NAME=$(echo "$GITHUB_REPOSITORY" | cut -d '/' -f 2)

          {
            echo 'cask "sogou-input" do'
            echo "  version \"${VERSION}\""
            echo "  sha256 \"${SHA256}\""
            echo ""
            echo -n '  url "https://github.com/'
            echo -n "${REPO_OWNER}/${REPO_NAME}"
            echo -n '/releases/download/'
            echo 'v#{version}/sogou_input_v#{version}.zip"'
            echo "  name \"Sogou Input Method\""
            echo "  desc \"Chinese input method\""
            echo "  homepage \"https://pinyin.sogou.com/mac/\""
            echo ""
            echo "  livecheck do"
            echo -n "    url \"https://github.com/"
            echo -n "${REPO_OWNER}/"
            echo "${REPO_NAME}/releases\""
            echo "    regex(/v?(\\d+(?:\\.\\d+)+)/i)"
            echo "  end"
            echo ""
            echo "  auto_updates true"
            echo "  depends_on macos: \">= :mojave\""
            echo "  depends_on arch: [:x86_64, :arm64]"
            echo "  stage_only true"
            echo ""
            echo "  postflight do"
            echo -n '    app_path = Dir['
            echo '"#{staged_path}/sogou*.app"].first'
            echo "    if app_path.nil?"
            echo -n '      puts '
            echo '"No Sogou app found in #{staged_path}"'
            echo "    else"
            echo "      system \"/usr/bin/open\", app_path"
            echo "    end"
            echo "  end"
            echo "end"
          } > Casks/sogou-input.rb

      - name: Commit and push changes
        if: ${{ env.SKIP_RELEASE != 'true' }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Casks/sogou-input.rb
          git commit -m "Update Sogou Input to v$VERSION"
          git push
